import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

const _unicodeVersion = '17.0.0';
const _sourceSha256 =
    'ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183';
const _sourceUrl =
    'https://www.unicode.org/Public/$_unicodeVersion/ucd/CaseFolding.txt';

/// Regenerates the bundled table offline from the verified upstream fixture.
void main() {
  final source = File.fromUri(
    Platform.script.resolve('CaseFolding-$_unicodeVersion.txt'),
  );
  final bytes = source.readAsBytesSync();
  if (sha256.convert(bytes).toString() != _sourceSha256) {
    throw StateError('Unicode source hash differs from the pinned release.');
  }

  final mappings = <({int source, int target})>[];
  for (final line in const LineSplitter().convert(utf8.decode(bytes))) {
    if (line.isEmpty || line.startsWith('#')) continue;

    final fields = line.split(';').map((field) => field.trim()).toList();
    if (fields[1] != 'C' && fields[1] != 'S') continue;

    mappings.add((
      source: int.parse(fields[0], radix: 16),
      target: int.parse(fields[2], radix: 16),
    ));
  }

  // Collapse equal offsets at stride 1 or 2; ranges never overlap.
  final ranges = <({int start, int end, int stride, int delta})>[];
  for (var index = 0; index < mappings.length;) {
    final first = mappings[index];
    final delta = first.target - first.source;
    var end = index;
    var stride = 1;
    if (index + 1 < mappings.length) {
      final next = mappings[index + 1];
      final distance = next.source - first.source;
      if (distance <= 2 && next.target - next.source == delta) {
        stride = distance;
        end++;
      }
    }
    while (end + 1 < mappings.length &&
        mappings[end + 1].source - mappings[end].source == stride &&
        mappings[end + 1].target - mappings[end + 1].source == delta) {
      end++;
    }
    ranges.add((
      start: first.source,
      end: mappings[end].source,
      stride: stride,
      delta: delta,
    ));
    index = end + 1;
  }

  final output = StringBuffer()
    ..writeln('// Generated by tool/unicode/generate.dart. Do not edit.')
    ..writeln('// Source: $_sourceUrl')
    ..writeln('// SHA-256: $_sourceSha256')
    ..writeln(
      '// Copyright © 2025 Unicode, Inc. License: tool/unicode/LICENSE.txt',
    )
    ..writeln()
    ..writeln("part of 'unicode_simple_fold.dart';")
    ..writeln()
    ..writeln('// One range per constant offset; stride 2 skips uncased gaps.')
    ..writeln('// dart format off')
    ..writeln(
      'const _foldRanges = <({int start, int end, int stride, int delta})>[',
    );
  for (final range in ranges) {
    output.writeln(
      '  (start: ${_hex(range.start)}, end: ${_hex(range.end)}, '
      'stride: ${range.stride}, delta: ${range.delta}),',
    );
  }
  output.writeln('];');

  final destination = File.fromUri(
    Platform.script.resolve(
      '../../lib/src/browse/unicode_simple_fold_data.dart',
    ),
  );
  destination.writeAsStringSync(output.toString());
  stdout.writeln('${mappings.length} mappings in ${ranges.length} ranges.');
}

String _hex(int value) => '0x${value.toRadixString(16)}';
