import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

const _unicodeVersion = '17.0.0';
const _unicodeDataSha256 =
    '2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c';
const _caseFoldingSha256 =
    'ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183';
const _unicodeDataUrl =
    'https://www.unicode.org/Public/$_unicodeVersion/ucd/UnicodeData.txt';
const _caseFoldingUrl =
    'https://www.unicode.org/Public/$_unicodeVersion/ucd/CaseFolding.txt';

/// Regenerates the bundled type-ahead fold table offline from the verified
/// upstream fixtures.
void main() {
  final decompositions = <int, List<int>>{};
  final marks = <int>{};

  final unicodeData = _readVerified(
    'UnicodeData-$_unicodeVersion.txt',
    _unicodeDataSha256,
  );
  for (final line in const LineSplitter().convert(utf8.decode(unicodeData))) {
    if (line.isEmpty || line.startsWith('#')) continue;

    final fields = line.split(';').map((field) => field.trim()).toList();
    final point = int.parse(fields[0], radix: 16);
    // Diacritic stripping removes non-spacing and enclosing marks; spacing
    // marks (Mc) carry Indic vowels and are text, not decoration.
    if (fields[2] == 'Mn' || fields[2] == 'Me') marks.add(point);

    final decomposition = fields[5];
    if (decomposition.isNotEmpty && !decomposition.startsWith('<')) {
      decompositions[point] = [
        for (final part in decomposition.split(' '))
          int.parse(part, radix: 16),
      ];
    }
  }

  final folding = <int, int>{};
  final caseFolding = _readVerified(
    'CaseFolding-$_unicodeVersion.txt',
    _caseFoldingSha256,
  );
  for (final line in const LineSplitter().convert(
    utf8.decode(caseFolding),
  )) {
    if (line.isEmpty || line.startsWith('#')) continue;

    final fields = line.split(';').map((field) => field.trim()).toList();
    if (fields[1] != 'C' && fields[1] != 'S') continue;

    folding[int.parse(fields[0], radix: 16)] = int.parse(
      fields[2],
      radix: 16,
    );
  }

  // The fold result of one code point: recursively canonically decompose
  // (UnicodeData carries no Hangul syllable decompositions — the runtime
  // fold applies the Unicode §3.12 conjoining-jamo formula), drop marks,
  // then apply each survivor's simple fold.
  List<int> foldPoint(int point) {
    final expanded = <int>[];
    void decompose(int current) {
      final parts = decompositions[current];
      if (parts == null) {
        expanded.add(current);
      } else {
        for (final part in parts) {
          decompose(part);
        }
      }
    }

    decompose(point);
    return [
      for (final current in expanded)
        if (!marks.contains(current)) folding[current] ?? current,
    ];
  }

  final table = <int, List<int>>{};
  for (final point in <int>{
    ...decompositions.keys,
    ...marks,
    ...folding.keys,
  }) {
    final result = foldPoint(point);
    if (result.length != 1 || result.single != point) {
      table[point] = List.unmodifiable(result);
    }
  }

  final output = StringBuffer()
    ..writeln('// Generated by tool/unicode/generate.dart. Do not edit.')
    ..writeln('// Sources: $_unicodeDataUrl')
    ..writeln('//          $_caseFoldingUrl')
    ..writeln('// SHA-256: $_unicodeDataSha256 (UnicodeData)')
    ..writeln('// SHA-256: $_caseFoldingSha256 (CaseFolding)')
    ..writeln(
      '// Copyright © 2025 Unicode, Inc. License: tool/unicode/LICENSE.txt',
    )
    ..writeln()
    ..writeln("part of 'unicode_diacritic_fold.dart';")
    ..writeln()
    ..writeln('// Code points whose decompose -> strip marks -> fold pipeline')
    ..writeln('// changes them. Values are the replacement code points; an')
    ..writeln('// empty list strips the mark outright.')
    ..writeln('// dart format off')
    ..writeln('const _diacriticFoldTable = <int, List<int>>{');
  for (final entry in table.entries.toList()
    ..sort((a, b) => a.key.compareTo(b.key))) {
    output.writeln(
      '  ${_hex(entry.key)}: [${entry.value.map(_hex).join(', ')}],',
    );
  }
  output.writeln('};');

  final destination = File.fromUri(
    Platform.script.resolve(
      '../../lib/services/unicode_diacritic_fold_data.dart',
    ),
  );
  destination.writeAsStringSync(output.toString());
  stdout.writeln('${table.length} fold entries.');
}

List<int> _readVerified(String name, String expectedSha256) {
  final source = File.fromUri(Platform.script.resolve(name));
  final bytes = source.readAsBytesSync();
  if (sha256.convert(bytes).toString() != expectedSha256) {
    throw StateError('Unicode source hash differs from the pinned release.');
  }
  return bytes;
}

String _hex(int value) => '0x${value.toRadixString(16)}';
